export const RESPONSE_MESSAGE = Object.freeze({
	BAD_REQUEST: 'BAD_REQUEST',
	UNAUTHORIZED: 'UNAUTHORIZED',
	TOKEN_INVALID: 'TOKEN_INVALID',
	TOKEN_EXPIRED: 'TOKEN_EXPIRED',
	TOKEN_STEALING: 'TOKEN_STEALING',
	ORDER_SESSION_EXPIRED: 'ORDER_SESSION_EXPIRED',
	FORBIDDEN: 'FORBIDDEN',
	CONFLICT: 'CONFLICT',
	UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	ORDER_DATA_FAILED: 'ORDER_DATA_FAILED',
	DB_CONNECTION_ERROR: 'DB_CONNECTION_ERROR',
} as const);

export type ResponseMessage = (typeof RESPONSE_MESSAGE)[keyof typeof RESPONSE_MESSAGE];